# Generated by Django 5.2.8 on 2026-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grammar_mastery',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='listening_mastery',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='q_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vocab_mastery',
            field=models.FloatField(default=0.1),
        ),
    ]
