# Generated by Django 5.2.8 on 2026-04-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_userprofile_grammar_mastery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_logs', to='learning.userprofile')),
            ],
        ),
    ]
