# Generated by Django 5.2.8 on 2026-04-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_masterylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasteryLog',
        ),
    ]
