# Generated by Django 5.2.8 on 2026-04-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_userprofile_completion_rate_and_more'),
        ('learning', '0004_delete_masterylog'),
    ]

    operations = [
    ]
