# Generated by Django 5.2.8 on 2026-04-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_merge_20260416_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='exercise_streak',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='knowledge_trace',
        ),
    ]
