# Generated by Django 5.2.8 on 2026-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_remove_userprofile_completion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('order_num', models.IntegerField(default=1)),
                ('content_html', models.TextField()),
            ],
            options={
                'ordering': ['level', 'order_num'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='media_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
